### ISSUE TITLE
请交换三个按钮的位置，以符合anki 本身的使用习惯。

### ISSUE THREAD

**Issue by wangcb80** [lovac42/Cronholio#1]
请交换三个按钮的位置，以符合anki 本身的使用习惯。anki按钮的使用习惯是从左到右的难度系数是渐小的。如果依然按照你的方式排列各按钮的位置，在使用的过程中很可能会把需要再次复习的卡片按了F1快捷键（anki 中F1默认是再次马上复习），结果却是删除了这个卡片（你的插件是在你的表中删除这个卡片，不再按排再次复习）。这对使用者造成困扰，必须每次小心的看按钮是你的插件的，还是anki本身的。

按钮交换后代码为（我在你的代码上改了一下）：
def answerButtonList(self, _old):
    if not cronholio.cronCard:
        return _old(self)
    return((1, _('NxCron')),(2, _('Skip')),(3, _('UnCron'))  )

但各按钮的功能依然如旧，我不会了！哈哈！你能修改一下吗？？谢谢！

**Comment by lovac42** [comment]
nxCron should be the default when the user hits enter.
maybe 1 for Skip, 2 for nxCron, and 3 for UnCron?

edit: The card didn't get delete, it's just shuffled to the back of the queue. Refresh the reviewer and you should will see it again.

**Comment by wangcb80** [comment]
I think it's the best：1 for NxCron, 2 for Skip, and 3 for UnCron

**Comment by lovac42** [comment]
If you're asking this just for yourself, you can change it in main.py on lines 72 and 74. Just change ease==1 2 or 3 for buttons 1,2,3. I will reconsider this if others have the same problem.

**Comment by wangcb80** [comment]
Thank you very much! I've changed it.

**Comment by wangcb80** [comment]
我修改了快捷键，然后并不起作用，为什么：
const.py 
# == User Config =========================================
HOTKEY = 'Ctrl+R'
